{"name":"Log","hostname":"RP","pid":26741,"level":50,"err":{"id":"9c4df580-a377-11e7-bbf7-7f2fa5832dbb","domain":"http://localhost:2368","code":"ER_DBACCESS_DENIED_ERROR","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at /home/www/ghost/index.js:38:15\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/www/ghost/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/www/ghost/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)\n\nError: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ghost'@'localhost' to database 'ghost'\n    at Handshake.Sequence._packetToError (/home/www/ghost/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/home/www/ghost/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)\n    at Protocol._parsePacket (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/home/www/ghost/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/home/www/ghost/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:547:20)\n    --------------------\n    at Protocol._enqueue (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/home/www/ghost/node_modules/mysql/lib/Connection.js:130:18)\n    at /home/www/ghost/node_modules/knex/lib/dialects/mysql/index.js:106:18\n    at Promise._execute (/home/www/ghost/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/home/www/ghost/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL.acquireRawConnection (/home/www/ghost/node_modules/knex/lib/dialects/mysql/index.js:104:12)\n    at Object.create (/home/www/ghost/node_modules/knex/lib/client.js:239:16)\n    at Pool._createResource (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:354:17)\n    at Pool.dispense [as _dispense] (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:314:10)\n    at Pool.acquire (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:436:8)\n    at /home/www/ghost/node_modules/knex/lib/client.js:289:19\n    at Promise._execute (/home/www/ghost/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/home/www/ghost/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:79:10)"},"msg":"The server has encountered an error.","time":"2017-09-27T11:32:57.698Z","v":0}
{"name":"Log","hostname":"RP","pid":26741,"level":50,"err":{"id":"9c4df580-a377-11e7-bbf7-7f2fa5832dbb","domain":"http://localhost:2368","code":"ER_DBACCESS_DENIED_ERROR","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at /home/www/ghost/index.js:38:15\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/www/ghost/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/www/ghost/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)\n\nError: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ghost'@'localhost' to database 'ghost'\n    at Handshake.Sequence._packetToError (/home/www/ghost/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/home/www/ghost/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)\n    at Protocol._parsePacket (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/home/www/ghost/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/home/www/ghost/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:547:20)\n    --------------------\n    at Protocol._enqueue (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/home/www/ghost/node_modules/mysql/lib/Connection.js:130:18)\n    at /home/www/ghost/node_modules/knex/lib/dialects/mysql/index.js:106:18\n    at Promise._execute (/home/www/ghost/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/home/www/ghost/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL.acquireRawConnection (/home/www/ghost/node_modules/knex/lib/dialects/mysql/index.js:104:12)\n    at Object.create (/home/www/ghost/node_modules/knex/lib/client.js:239:16)\n    at Pool._createResource (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:354:17)\n    at Pool.dispense [as _dispense] (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:314:10)\n    at Pool.acquire (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:436:8)\n    at /home/www/ghost/node_modules/knex/lib/client.js:289:19\n    at Promise._execute (/home/www/ghost/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/home/www/ghost/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:79:10)"},"msg":"The server has encountered an error.","time":"2017-09-27T11:32:57.698Z","v":0}
{"name":"Log","hostname":"RP","pid":26787,"level":50,"err":{"id":"420f9fe0-a379-11e7-af47-1b5ba55acd44","domain":"http://localhost:2368","code":"ER_DBACCESS_DENIED_ERROR","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at /home/www/ghost/index.js:38:15\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/www/ghost/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/www/ghost/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)\n\nError: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ghost'@'localhost' to database 'ghost'\n    at Handshake.Sequence._packetToError (/home/www/ghost/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/home/www/ghost/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)\n    at Protocol._parsePacket (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/home/www/ghost/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/home/www/ghost/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:547:20)\n    --------------------\n    at Protocol._enqueue (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/home/www/ghost/node_modules/mysql/lib/Connection.js:130:18)\n    at /home/www/ghost/node_modules/knex/lib/dialects/mysql/index.js:106:18\n    at Promise._execute (/home/www/ghost/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/home/www/ghost/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL.acquireRawConnection (/home/www/ghost/node_modules/knex/lib/dialects/mysql/index.js:104:12)\n    at Object.create (/home/www/ghost/node_modules/knex/lib/client.js:239:16)\n    at Pool._createResource (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:354:17)\n    at Pool.dispense [as _dispense] (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:314:10)\n    at Pool.acquire (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:436:8)\n    at /home/www/ghost/node_modules/knex/lib/client.js:289:19\n    at Promise._execute (/home/www/ghost/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/home/www/ghost/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:79:10)"},"msg":"The server has encountered an error.","time":"2017-09-27T11:44:45.288Z","v":0}
{"name":"Log","hostname":"RP","pid":26787,"level":50,"err":{"id":"420f9fe0-a379-11e7-af47-1b5ba55acd44","domain":"http://localhost:2368","code":"ER_DBACCESS_DENIED_ERROR","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at /home/www/ghost/index.js:38:15\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/www/ghost/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/www/ghost/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)\n\nError: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ghost'@'localhost' to database 'ghost'\n    at Handshake.Sequence._packetToError (/home/www/ghost/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/home/www/ghost/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)\n    at Protocol._parsePacket (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/home/www/ghost/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/home/www/ghost/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:547:20)\n    --------------------\n    at Protocol._enqueue (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/home/www/ghost/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/home/www/ghost/node_modules/mysql/lib/Connection.js:130:18)\n    at /home/www/ghost/node_modules/knex/lib/dialects/mysql/index.js:106:18\n    at Promise._execute (/home/www/ghost/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/home/www/ghost/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL.acquireRawConnection (/home/www/ghost/node_modules/knex/lib/dialects/mysql/index.js:104:12)\n    at Object.create (/home/www/ghost/node_modules/knex/lib/client.js:239:16)\n    at Pool._createResource (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:354:17)\n    at Pool.dispense [as _dispense] (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:314:10)\n    at Pool.acquire (/home/www/ghost/node_modules/generic-pool/lib/generic-pool.js:436:8)\n    at /home/www/ghost/node_modules/knex/lib/client.js:289:19\n    at Promise._execute (/home/www/ghost/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/home/www/ghost/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:79:10)"},"msg":"The server has encountered an error.","time":"2017-09-27T11:44:45.288Z","v":0}
{"name":"Log","hostname":"RP","pid":26818,"level":50,"err":{"id":200,"domain":"http://localhost:2368","code":"MIGRATION_TABLE_IS_MISSING","name":"DatabaseIsNotOkError","statusCode":500,"level":"normal","message":"Please run knex-migrator init","help":"If knex-migrator is not installed, please run \"npm install -g knex-migrator\" \nRead more here: https://github.com/TryGhost/knex-migrator","stack":"DatabaseIsNotOkError: Please run knex-migrator init\n    at DatabaseIsNotOkError.KnexMigrateError (/home/www/ghost/node_modules/knex-migrator/lib/errors.js:7:26)\n    at new DatabaseIsNotOkError (/home/www/ghost/node_modules/knex-migrator/lib/errors.js:19:26)\n    at onMigrationsLookupError (/home/www/ghost/node_modules/knex-migrator/lib/index.js:564:23)\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/www/ghost/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/www/ghost/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"},"msg":"Please run knex-migrator init","time":"2017-09-27T11:47:00.025Z","v":0}
{"name":"Log","hostname":"RP","pid":26818,"level":50,"err":{"id":200,"domain":"http://localhost:2368","code":"MIGRATION_TABLE_IS_MISSING","name":"DatabaseIsNotOkError","statusCode":500,"level":"normal","message":"Please run knex-migrator init","help":"If knex-migrator is not installed, please run \"npm install -g knex-migrator\" \nRead more here: https://github.com/TryGhost/knex-migrator","stack":"DatabaseIsNotOkError: Please run knex-migrator init\n    at DatabaseIsNotOkError.KnexMigrateError (/home/www/ghost/node_modules/knex-migrator/lib/errors.js:7:26)\n    at new DatabaseIsNotOkError (/home/www/ghost/node_modules/knex-migrator/lib/errors.js:19:26)\n    at onMigrationsLookupError (/home/www/ghost/node_modules/knex-migrator/lib/index.js:564:23)\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/www/ghost/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/www/ghost/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"},"msg":"Please run knex-migrator init","time":"2017-09-27T11:47:00.025Z","v":0}
{"name":"Log","hostname":"RP","pid":28745,"level":50,"err":{"id":"ced248b0-a3e7-11e7-bda1-b7790a521fce","domain":"http://localhost:2368","code":"SQLITE_CANTOPEN","name":"InternalServerError","statusCode":500,"level":"normal","message":"The server has encountered an error.","stack":"InternalServerError: The server has encountered an error.\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at /home/www/ghost/index.js:38:15\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/www/ghost/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/www/ghost/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)\n\nError: SQLITE_CANTOPEN: unable to open database file\n    at Error (native)"},"msg":"The server has encountered an error.","time":"2017-09-28T00:56:06.084Z","v":0}
