{"name":"Log","hostname":"RP","pid":23252,"level":50,"req":{"meta":{"requestId":"62306bd0-28f1-11e8-b404-ef907617b73f","userId":null},"url":"/authentication/token","method":"POST","originalUrl":"/ghost/api/v0.1/authentication/token","params":{},"headers":{"x-forwarded-for":"219.239.227.233","x-real-ip":"219.239.227.233","host":"47.95.197.107","x-forwarded-proto":"http","connection":"close","content-length":"230","origin":"http://47.95.197.107","app-pragma":"no-cache","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ghost-desktop/1.4.0 Chrome/58.0.3029.110 Electron/1.7.6 Safari/537.36","content-type":"application/x-www-form-urlencoded","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","x-ghost-version":"1.10","referer":"http://47.95.197.107/ghost/","accept-encoding":"gzip, deflate","accept-language":"zh-CN"},"body":{"grant_type":"refresh_token","refresh_token":"ETuVyRfsUaeiXS8LlNNf02IcvxjjUWhDCM37BOKMuFyLo43p32k5PNaqgeLws8OL4gb4kywcyw62D69OzHae9lSkMOfsKavkfiLMQFDc2yZOR58oVdrmya2zZIGpe8tHNp8n8eDRE64PNnRHkkLB313G6CXydePCV0Q819xFgPAzhK5wsvTrbS4Y81l3MaF"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","content-type":"application/json; charset=utf-8","content-length":"122","etag":"W/\"7a-CFzaauITpDwLceugs9PLp/pF9SM\"","vary":"Accept-Encoding"},"statusCode":401,"responseTime":"59ms"},"err":{"id":"62394570-28f1-11e8-b404-ef907617b73f","domain":"http://47.95.197.107:2368","code":null,"name":"UnauthorizedError","statusCode":401,"level":"normal","message":"Access denied.","context":"Client credentials were not provided","help":"For information on how to fix this, please read http://api.ghost.org/docs/client-authentication.","stack":"UnauthorizedError: Access denied.\n    at new UnauthorizedError (/home/www/ghost/node_modules/ghost-ignition/lib/errors/index.js:101:23)\n    at authenticateClient (/home/www/ghost/core/server/auth/authenticate.js:26:25)\n    at Layer.handle [as handle_request] (/home/www/ghost/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/www/ghost/node_modules/express/lib/router/route.js:137:13)\n    at .<anonymous> (/home/www/ghost/node_modules/express-brute/index.js:142:36)\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise.successAdapter [as _fulfillmentHandler0] (/home/www/ghost/node_modules/bluebird/js/release/nodeify.js:23:30)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:566:21)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/home/www/ghost/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/www/ghost/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"},"msg":"Access denied.","time":"2018-03-16T08:09:43.498Z","v":0}
{"name":"Log","hostname":"RP","pid":23252,"level":50,"req":{"meta":{"requestId":"7aa82770-28f1-11e8-b404-ef907617b73f","userId":null},"url":"/authentication/token","method":"POST","originalUrl":"/ghost/api/v0.1/authentication/token","params":{},"headers":{"x-forwarded-for":"219.239.227.233","x-real-ip":"219.239.227.233","host":"47.95.197.107","x-forwarded-proto":"http","connection":"close","content-length":"123","origin":"http://47.95.197.107","app-pragma":"no-cache","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ghost-desktop/1.4.0 Chrome/58.0.3029.110 Electron/1.7.6 Safari/537.36","content-type":"application/x-www-form-urlencoded","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","x-ghost-version":"1.10","referer":"http://47.95.197.107/ghost/","accept-encoding":"gzip, deflate","accept-language":"zh-CN"},"body":{"grant_type":"password","username":"10041051@buaa.edu.cn"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","content-type":"application/json; charset=utf-8","content-length":"124","etag":"W/\"7c-ivmlgJsSiTOhqS5rH3IOo3nuoXE\"","vary":"Accept-Encoding"},"statusCode":422,"responseTime":"140ms"},"err":{"id":"7abd5d20-28f1-11e8-b404-ef907617b73f","domain":"http://47.95.197.107:2368","code":"PASSWORD_INCORRECT","name":"ValidationError","statusCode":422,"level":"normal","message":"Your password is incorrect.","context":"Your password is incorrect.","help":"Visit and save your profile after logging in to check for problems.","stack":"ValidationError: Your password is incorrect.\n    at new ValidationError (/home/www/ghost/node_modules/ghost-ignition/lib/errors/index.js:115:23)\n    at /home/www/ghost/core/server/models/user.js:734:39\n    at tryCatcher (/home/www/ghost/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/www/ghost/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/www/ghost/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/www/ghost/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/www/ghost/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/home/www/ghost/node_modules/bluebird/js/release/promise.js:638:18)\n    at /home/www/ghost/node_modules/bluebird/js/release/nodeback.js:42:21\n    at /home/www/ghost/node_modules/bcryptjs/dist/bcrypt.js:297:21\n    at /home/www/ghost/node_modules/bcryptjs/dist/bcrypt.js:1353:21\n    at Immediate.next (/home/www/ghost/node_modules/bcryptjs/dist/bcrypt.js:1233:21)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"},"msg":"Your password is incorrect.","time":"2018-03-16T08:10:24.630Z","v":0}
{"name":"Log","hostname":"RP","pid":23252,"level":50,"err":{"id":"65727aa0-28f5-11e8-b404-ef907617b73f","domain":"http://47.95.197.107:2368","code":"ETIMEDOUT","name":"InternalServerError","statusCode":500,"level":"normal","message":"connect ETIMEDOUT 172.217.160.100:80","context":"Pinging services for updates on your blog failed, your blog will continue to function.","help":"If you get this error repeatedly, please seek help on http://docs.ghost.org.","stack":"InternalServerError: connect ETIMEDOUT 172.217.160.100:80\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at ClientRequest.handleError (/home/www/ghost/core/server/data/xml/xmlrpc.js:81:27)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at Socket.socketErrorListener (_http_client.js:310:9)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n\nError: connect ETIMEDOUT 172.217.160.100:80\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)"},"msg":"connect ETIMEDOUT 172.217.160.100:80","time":"2018-03-16T08:38:26.891Z","v":0}
{"name":"Log","hostname":"RP","pid":23252,"level":50,"err":{"id":"b6788390-28f5-11e8-b404-ef907617b73f","domain":"http://47.95.197.107:2368","code":"ETIMEDOUT","name":"InternalServerError","statusCode":500,"level":"normal","message":"connect ETIMEDOUT 172.217.160.100:80","context":"Pinging services for updates on your blog failed, your blog will continue to function.","help":"If you get this error repeatedly, please seek help on http://docs.ghost.org.","stack":"InternalServerError: connect ETIMEDOUT 172.217.160.100:80\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at ClientRequest.handleError (/home/www/ghost/core/server/data/xml/xmlrpc.js:81:27)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at Socket.socketErrorListener (_http_client.js:310:9)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n\nError: connect ETIMEDOUT 172.217.160.100:80\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)"},"msg":"connect ETIMEDOUT 172.217.160.100:80","time":"2018-03-16T08:40:42.826Z","v":0}
{"name":"Log","hostname":"RP","pid":23252,"level":50,"err":{"id":"24690b90-28f6-11e8-b404-ef907617b73f","domain":"http://47.95.197.107:2368","code":"ETIMEDOUT","name":"InternalServerError","statusCode":500,"level":"normal","message":"connect ETIMEDOUT 172.217.160.100:80","context":"Pinging services for updates on your blog failed, your blog will continue to function.","help":"If you get this error repeatedly, please seek help on http://docs.ghost.org.","stack":"InternalServerError: connect ETIMEDOUT 172.217.160.100:80\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at ClientRequest.handleError (/home/www/ghost/core/server/data/xml/xmlrpc.js:81:27)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at Socket.socketErrorListener (_http_client.js:310:9)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n\nError: connect ETIMEDOUT 172.217.160.100:80\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)"},"msg":"connect ETIMEDOUT 172.217.160.100:80","time":"2018-03-16T08:43:47.275Z","v":0}
{"name":"Log","hostname":"RP","pid":23252,"level":50,"err":{"id":"afcca390-28f6-11e8-b404-ef907617b73f","domain":"http://47.95.197.107:2368","code":"ETIMEDOUT","name":"InternalServerError","statusCode":500,"level":"normal","message":"connect ETIMEDOUT 216.58.200.36:80","context":"Pinging services for updates on your blog failed, your blog will continue to function.","help":"If you get this error repeatedly, please seek help on http://docs.ghost.org.","stack":"InternalServerError: connect ETIMEDOUT 216.58.200.36:80\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at ClientRequest.handleError (/home/www/ghost/core/server/data/xml/xmlrpc.js:81:27)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at Socket.socketErrorListener (_http_client.js:310:9)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n\nError: connect ETIMEDOUT 216.58.200.36:80\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)"},"msg":"connect ETIMEDOUT 216.58.200.36:80","time":"2018-03-16T08:47:41.131Z","v":0}
{"name":"Log","hostname":"RP","pid":23252,"level":50,"err":{"id":"435a1390-28f7-11e8-b404-ef907617b73f","domain":"http://47.95.197.107:2368","code":"ETIMEDOUT","name":"InternalServerError","statusCode":500,"level":"normal","message":"connect ETIMEDOUT 216.58.200.36:80","context":"Pinging services for updates on your blog failed, your blog will continue to function.","help":"If you get this error repeatedly, please seek help on http://docs.ghost.org.","stack":"InternalServerError: connect ETIMEDOUT 216.58.200.36:80\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at ClientRequest.handleError (/home/www/ghost/core/server/data/xml/xmlrpc.js:81:27)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at Socket.socketErrorListener (_http_client.js:310:9)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n\nError: connect ETIMEDOUT 216.58.200.36:80\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)"},"msg":"connect ETIMEDOUT 216.58.200.36:80","time":"2018-03-16T08:51:48.682Z","v":0}
{"name":"Log","hostname":"RP","pid":23252,"level":50,"err":{"id":"c42a4aa0-2918-11e8-b404-ef907617b73f","domain":"http://47.95.197.107:2368","code":"ETIMEDOUT","name":"InternalServerError","statusCode":500,"level":"normal","message":"connect ETIMEDOUT 172.217.160.68:80","context":"Pinging services for updates on your blog failed, your blog will continue to function.","help":"If you get this error repeatedly, please seek help on http://docs.ghost.org.","stack":"InternalServerError: connect ETIMEDOUT 172.217.160.68:80\n    at new GhostError (/home/www/ghost/core/server/errors.js:9:26)\n    at ClientRequest.handleError (/home/www/ghost/core/server/data/xml/xmlrpc.js:81:27)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at Socket.socketErrorListener (_http_client.js:310:9)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n\nError: connect ETIMEDOUT 172.217.160.68:80\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)"},"msg":"connect ETIMEDOUT 172.217.160.68:80","time":"2018-03-16T12:51:38.188Z","v":0}
